[package]
authors = ["Pavel Aslanov <asl.pavel@gmail.com>"]
build = "build.rs"
edition = "2018"
name = "sweep"
version = "0.1.0"

[lib]
name = "sweep_lib"
path = "src/lib.rs"

[[bin]]
name = "sweep"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.*"
clap = "2.33"
nix = "0.18"
rayon = "1.4"
serde_json = "1.0"
surf_n_term = {git = "https://github.com/aslpavel/surf-n-term.git", branch = "main"}

[dev-dependencies]
criterion = "0.3.*"

[[bench]]
harness = false
name = "scorer"
