[package]
authors = ["Pavel Aslanov <asl.pavel@gmail.com>"]
build = "build.rs"
edition = "2018"
name = "sweep"
version = "0.2.0"

[lib]
name = "sweep"
path = "src/lib.rs"

[[bin]]
name = "sweep"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
argh = "0.1"
crossbeam-channel = "0.5"
nix = "0.20"
rayon = "1.5"
serde_json = "1.0"
surf_n_term = "^0.1.4"
# surf_n_term = {path = "../surf-n-term"}

[dev-dependencies]
criterion = "0.3"

[[bench]]
harness = false
name = "scorer"
