[package]
name = "sweep"
version = "0.1.0"
authors = ["Pavel Aslanov <asl.pavel@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
name = "sweep_lib"
path = "src/lib.rs"

[[bin]]
name = "sweep"
path = "src/main.rs"

[dependencies]
surf_n_term = { path = "../" }
rayon = "1.3.1"
clap = "2.33.1"
anyhow = "1.0.*"
nix = "0.17.0"
serde_json = "1.0.56"

[dev-dependencies]
criterion = "0.3.*"

[[bench]]
name = "scorer"
harness = false
